### ISSUE TITLE
Allow creating a user from the admin interface

### ISSUE THREAD

**Issue by 0x52a1** [peopleagainstprisons/earmms#31]
PAPA allows for incarcerated people to become members. Since those people can not access the internet and create their own user accounts, the membership admin needs to be able to create those users. 

Users created through the membership admin interface should be permitted to have no associated email address. The membership admin should be able to associate an email address with the account in the future (in the example of incarcerated members, when they are released), and send a password reset email.

## To-do

* [x] Add form to `/admin/user` to create a user with a field for the user's name, redirecting to `/admin/user/:id`
* [x] Add button to `/admin/user/:id` to set email address and password to nil
* [x] Add a check to `/admin/user/:id` password reset to disallow trying to password reset a user with no email address
