### ISSUE TITLE
Only convert meeting attendance to guest when deleting account

### ISSUE THREAD

**Issue by 0x52a1** [peopleagainstprisons/earmms#35]
Meeting attendance for a user should continue to be displayed in previous branch meetings even after a user has changed their branch. This would also allow the membership admin view to display all meetings the user has attended, even after switching branch or membership status.

## To-do

This is probably incomplete.

* [x] Change `get_users_for_branch_meeting` to get the list of users who have already had an attendance record saved for the given meeting even if they aren't still a member of the branch, and merge that with the list of users currently in the branch
* [x] Change `BranchAdminUserAttendanceController` to only display attendance records from the given branch ID rather than all records
* [x] Change `MembershipAdminUserController` to remove `@user.convert_attendance_to_guest!` calls in membership status / branch editing
* [x] Change `MembershipAdminUserController` to display branch information in the user attendance log
